//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class myResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal myResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Languages.myResources", typeof(myResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string account {
            get {
                return ResourceManager.GetString("account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account details.
        /// </summary>
        internal static string accountDetails {
            get {
                return ResourceManager.GetString("accountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add department.
        /// </summary>
        internal static string addDepartment {
            get {
                return ResourceManager.GetString("addDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        internal static string addNew {
            get {
                return ResourceManager.GetString("addNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required!.
        /// </summary>
        internal static string addressRequired {
            get {
                return ResourceManager.GetString("addressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be less than {0} characters!.
        /// </summary>
        internal static string addressTooLong {
            get {
                return ResourceManager.GetString("addressTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string advancedSettings {
            get {
                return ResourceManager.GetString("advancedSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All departments.
        /// </summary>
        internal static string allDepartments {
            get {
                return ResourceManager.GetString("allDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcement.
        /// </summary>
        internal static string announcement {
            get {
                return ResourceManager.GetString("announcement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key.
        /// </summary>
        internal static string apiKey {
            get {
                return ResourceManager.GetString("apiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API key is unique code assigned to your company..
        /// </summary>
        internal static string apiKeyIsUnique {
            get {
                return ResourceManager.GetString("apiKeyIsUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string appointment {
            get {
                return ResourceManager.GetString("appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment settings.
        /// </summary>
        internal static string appointmentSettings {
            get {
                return ResourceManager.GetString("appointmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string available {
            get {
                return ResourceManager.GetString("available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time.
        /// </summary>
        internal static string averageTime {
            get {
                return ResourceManager.GetString("averageTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVG.
        /// </summary>
        internal static string avg {
            get {
                return ResourceManager.GetString("avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to doctor list.
        /// </summary>
        internal static string backDoctorList {
            get {
                return ResourceManager.GetString("backDoctorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billings.
        /// </summary>
        internal static string billings {
            get {
                return ResourceManager.GetString("billings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By appointment.
        /// </summary>
        internal static string byAppointment {
            get {
                return ResourceManager.GetString("byAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By ticket numbers &amp; the number restarts.
        /// </summary>
        internal static string byTicketNumbersAndTheNumberRestarts {
            get {
                return ResourceManager.GetString("byTicketNumbersAndTheNumberRestarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Ticket.
        /// </summary>
        internal static string callingTicket {
            get {
                return ResourceManager.GetString("callingTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string cancelled {
            get {
                return ResourceManager.GetString("cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Ticket.
        /// </summary>
        internal static string candidateTicket {
            get {
                return ResourceManager.GetString("candidateTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha invalid!.
        /// </summary>
        internal static string captchaInvalid {
            get {
                return ResourceManager.GetString("captchaInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder name.
        /// </summary>
        internal static string cardHolderName {
            get {
                return ResourceManager.GetString("cardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string cardNumber {
            get {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card number!.
        /// </summary>
        internal static string cardNumberInvalid {
            get {
                return ResourceManager.GetString("cardNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number is required!.
        /// </summary>
        internal static string cardNumberRequired {
            get {
                return ResourceManager.GetString("cardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number must be less than {0} characters!.
        /// </summary>
        internal static string cardNumberTooLong {
            get {
                return ResourceManager.GetString("cardNumberTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change avatar.
        /// </summary>
        internal static string changeAvatar {
            get {
                return ResourceManager.GetString("changeAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked In.
        /// </summary>
        internal static string checkedIn {
            get {
                return ResourceManager.GetString("checkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check-in.
        /// </summary>
        internal static string checkIn {
            get {
                return ResourceManager.GetString("checkIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We see that you have access to more than one organization. Please select one to continue..
        /// </summary>
        internal static string chooseAnOrgText {
            get {
                return ResourceManager.GetString("chooseAnOrgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose appointment.
        /// </summary>
        internal static string chooseAppointment {
            get {
                return ResourceManager.GetString("chooseAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date.
        /// </summary>
        internal static string chooseDate {
            get {
                return ResourceManager.GetString("chooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose doctor failed!.
        /// </summary>
        internal static string chooseDoctorFailed {
            get {
                return ResourceManager.GetString("chooseDoctorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose doctor successfully!.
        /// </summary>
        internal static string chooseDoctorSuccess {
            get {
                return ResourceManager.GetString("chooseDoctorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City must be less than {0} characters!.
        /// </summary>
        internal static string cityTooLong {
            get {
                return ResourceManager.GetString("cityTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click icons to view list.
        /// </summary>
        internal static string clickIconsToViewList {
            get {
                return ResourceManager.GetString("clickIconsToViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is invalid!.
        /// </summary>
        internal static string codeInvalid {
            get {
                return ResourceManager.GetString("codeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is required!.
        /// </summary>
        internal static string codeRequired {
            get {
                return ResourceManager.GetString("codeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required!.
        /// </summary>
        internal static string companyNameRequired {
            get {
                return ResourceManager.GetString("companyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name must be less than {0} characters!.
        /// </summary>
        internal static string companyNameTooLong {
            get {
                return ResourceManager.GetString("companyNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-generating API key may require some changes in your application..
        /// </summary>
        internal static string confirmGenerateAPIKey {
            get {
                return ResourceManager.GetString("confirmGenerateAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmination.
        /// </summary>
        internal static string confirmination {
            get {
                return ResourceManager.GetString("confirmination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string create {
            get {
                return ResourceManager.GetString("create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create failed!.
        /// </summary>
        internal static string createFailed {
            get {
                return ResourceManager.GetString("createFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create success!.
        /// </summary>
        internal static string createSuccess {
            get {
                return ResourceManager.GetString("createSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create ticket.
        /// </summary>
        internal static string createTicket {
            get {
                return ResourceManager.GetString("createTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        internal static string dateFormat {
            get {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yyyy.
        /// </summary>
        internal static string datePlaceHolder {
            get {
                return ResourceManager.GetString("datePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days of week.
        /// </summary>
        internal static string daysOfWeek {
            get {
                return ResourceManager.GetString("daysOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department exception.
        /// </summary>
        internal static string departmentException {
            get {
                return ResourceManager.GetString("departmentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have one or more departments that do not follow the company guideline for appointment, then this is a good place to tell us about those departments..
        /// </summary>
        internal static string departmentExceptionTooltip {
            get {
                return ResourceManager.GetString("departmentExceptionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name is required!.
        /// </summary>
        internal static string departmentNameRequired {
            get {
                return ResourceManager.GetString("departmentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department name must be less than {0} characters!.
        /// </summary>
        internal static string departmentNameTooLong {
            get {
                return ResourceManager.GetString("departmentNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name.
        /// </summary>
        internal static string displayName {
            get {
                return ResourceManager.GetString("displayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor List.
        /// </summary>
        internal static string doctorList {
            get {
                return ResourceManager.GetString("doctorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        internal static string dontHaveAnAccount {
            get {
                return ResourceManager.GetString("dontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download FREE App.
        /// </summary>
        internal static string downloadFreeApp {
            get {
                return ResourceManager.GetString("downloadFreeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email existed!.
        /// </summary>
        internal static string emailExisted {
            get {
                return ResourceManager.GetString("emailExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email!.
        /// </summary>
        internal static string emailInvalid {
            get {
                return ResourceManager.GetString("emailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone.
        /// </summary>
        internal static string emailOrPhone {
            get {
                return ResourceManager.GetString("emailOrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone invalid!.
        /// </summary>
        internal static string emailOrPhoneInvalid {
            get {
                return ResourceManager.GetString("emailOrPhoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone number.
        /// </summary>
        internal static string emailOrPhoneNumber {
            get {
                return ResourceManager.GetString("emailOrPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or phone is required!.
        /// </summary>
        internal static string emailOrPhoneRequired {
            get {
                return ResourceManager.GetString("emailOrPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required!.
        /// </summary>
        internal static string emailRequired {
            get {
                return ResourceManager.GetString("emailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email must be less than {0} characters!.
        /// </summary>
        internal static string emailTooLong {
            get {
                return ResourceManager.GetString("emailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter holiday name.
        /// </summary>
        internal static string enterHolidayName {
            get {
                return ResourceManager.GetString("enterHolidayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter it here for verification.
        /// </summary>
        internal static string enterItHereForVerification {
            get {
                return ResourceManager.GetString("enterItHereForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your code.
        /// </summary>
        internal static string enterYourCode {
            get {
                return ResourceManager.GetString("enterYourCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email or mobile phone number.
        /// </summary>
        internal static string enterYourEmailOrMobilePhoneNumber {
            get {
                return ResourceManager.GetString("enterYourEmailOrMobilePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expiration!.
        /// </summary>
        internal static string expDateInvalid {
            get {
                return ResourceManager.GetString("expDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration is required!.
        /// </summary>
        internal static string expDateRequired {
            get {
                return ResourceManager.GetString("expDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string expiration {
            get {
                return ResourceManager.GetString("expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstName {
            get {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required!.
        /// </summary>
        internal static string firstNameRequired {
            get {
                return ResourceManager.GetString("firstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name must be less than {0} characters!.
        /// </summary>
        internal static string firstNameTooLong {
            get {
                return ResourceManager.GetString("firstNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For businesses.
        /// </summary>
        internal static string forBusinesses {
            get {
                return ResourceManager.GetString("forBusinesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For everyone.
        /// </summary>
        internal static string forEveryOne {
            get {
                return ResourceManager.GetString("forEveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FREE 30 Days Trial.
        /// </summary>
        internal static string free30DaysTrial {
            get {
                return ResourceManager.GetString("free30DaysTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From date.
        /// </summary>
        internal static string fromDate {
            get {
                return ResourceManager.GetString("fromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string full {
            get {
                return ResourceManager.GetString("full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate API failed.
        /// </summary>
        internal static string generateAPIFailed {
            get {
                return ResourceManager.GetString("generateAPIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate API success.
        /// </summary>
        internal static string generateAPISuccess {
            get {
                return ResourceManager.GetString("generateAPISuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string go {
            get {
                return ResourceManager.GetString("go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder name.
        /// </summary>
        internal static string holderName {
            get {
                return ResourceManager.GetString("holderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder name is required!.
        /// </summary>
        internal static string holderNameRequired {
            get {
                return ResourceManager.GetString("holderNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holder name must be less than {0} characters!.
        /// </summary>
        internal static string holderNameTooLong {
            get {
                return ResourceManager.GetString("holderNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does your company receives customers?.
        /// </summary>
        internal static string howDoesYourCompanyReceivesCustomers {
            get {
                return ResourceManager.GetString("howDoesYourCompanyReceivesCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and I accept the Terms of Use and Privacy Statement.
        /// </summary>
        internal static string iReadAndAccept {
            get {
                return ResourceManager.GetString("iReadAndAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string lang_En {
            get {
                return ResourceManager.GetString("lang.En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        internal static string lang_Vi {
            get {
                return ResourceManager.GetString("lang.Vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastName {
            get {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required!.
        /// </summary>
        internal static string lastNameRequired {
            get {
                return ResourceManager.GetString("lastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name must be less than {0} characters!.
        /// </summary>
        internal static string lastNameTooLong {
            get {
                return ResourceManager.GetString("lastNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go &amp; make the customers HAPPY, shall we?.
        /// </summary>
        internal static string letGoMakeCustomerHappy {
            get {
                return ResourceManager.GetString("letGoMakeCustomerHappy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới hạn truy cập API, chỉ cho phép các IP bên dưới truy cập.
        /// </summary>
        internal static string limitAPIAccessToTheFollowingIPAddresses {
            get {
                return ResourceManager.GetString("limitAPIAccessToTheFollowingIPAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string logIn {
            get {
                return ResourceManager.GetString("logIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Appts.
        /// </summary>
        internal static string maxAppts {
            get {
                return ResourceManager.GetString("maxAppts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max waiting time after called.
        /// </summary>
        internal static string maxWaitingTimeAfterCalled {
            get {
                return ResourceManager.GetString("maxWaitingTimeAfterCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string message {
            get {
                return ResourceManager.GetString("message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum calendar time slot.
        /// </summary>
        internal static string minimumCalendarTimeSlot {
            get {
                return ResourceManager.GetString("minimumCalendarTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string mins {
            get {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More holiday.
        /// </summary>
        internal static string moreHoliday {
            get {
                return ResourceManager.GetString("moreHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More IP address.
        /// </summary>
        internal static string moreIPAddress {
            get {
                return ResourceManager.GetString("moreIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More shift.
        /// </summary>
        internal static string moreShift {
            get {
                return ResourceManager.GetString("moreShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network mask.
        /// </summary>
        internal static string networkMask {
            get {
                return ResourceManager.GetString("networkMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New email.
        /// </summary>
        internal static string newEmail {
            get {
                return ResourceManager.GetString("newEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required!.
        /// </summary>
        internal static string newPasswordRequired {
            get {
                return ResourceManager.GetString("newPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than {0} characters!.
        /// </summary>
        internal static string newPasswordTooLong {
            get {
                return ResourceManager.GetString("newPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string next {
            get {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No have slot.
        /// </summary>
        internal static string noHaveSlot {
            get {
                return ResourceManager.GetString("noHaveSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        internal static string noInformation {
            get {
                return ResourceManager.GetString("noInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Show.
        /// </summary>
        internal static string noShow {
            get {
                return ResourceManager.GetString("noShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not recognize your login. Please try again..
        /// </summary>
        internal static string notRecognizeLogin {
            get {
                return ResourceManager.GetString("notRecognizeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We still do not recognize your login. Please click on Forgot password below to get help..
        /// </summary>
        internal static string notRecognizeLoginAgain {
            get {
                return ResourceManager.GetString("notRecognizeLoginAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string oldPassword {
            get {
                return ResourceManager.GetString("oldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required!.
        /// </summary>
        internal static string oldPasswordRequired {
            get {
                return ResourceManager.GetString("oldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password must be less than {0} characters!.
        /// </summary>
        internal static string oldPasswordTooLong {
            get {
                return ResourceManager.GetString("oldPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only provide number tickets for.
        /// </summary>
        internal static string onlyProvideNumberTicketsFor {
            get {
                return ResourceManager.GetString("onlyProvideNumberTicketsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization settings.
        /// </summary>
        internal static string organizationSettings {
            get {
                return ResourceManager.GetString("organizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over booked.
        /// </summary>
        internal static string overBooked {
            get {
                return ResourceManager.GetString("overBooked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        internal static string passwordRequired {
            get {
                return ResourceManager.GetString("passwordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than {0} characters!.
        /// </summary>
        internal static string passwordTooLong {
            get {
                return ResourceManager.GetString("passwordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone!.
        /// </summary>
        internal static string phoneInvalid {
            get {
                return ResourceManager.GetString("phoneInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be less than {0} characters!.
        /// </summary>
        internal static string phoneTooLong {
            get {
                return ResourceManager.GetString("phoneTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be greater than {0} characters!.
        /// </summary>
        internal static string phoneTooShort {
            get {
                return ResourceManager.GetString("phoneTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password.
        /// </summary>
        internal static string pleaseEnterYourNewPassword {
            get {
                return ResourceManager.GetString("pleaseEnterYourNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in.
        /// </summary>
        internal static string pleaseLogIn {
            get {
                return ResourceManager.GetString("pleaseLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string refresh {
            get {
                return ResourceManager.GetString("refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-generate.
        /// </summary>
        internal static string reGenerate {
            get {
                return ResourceManager.GetString("reGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/State.
        /// </summary>
        internal static string region {
            get {
                return ResourceManager.GetString("region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region/State must be less than {0} characters!.
        /// </summary>
        internal static string regionTooLong {
            get {
                return ResourceManager.GetString("regionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind client before serving.
        /// </summary>
        internal static string remindClientBeforeServing {
            get {
                return ResourceManager.GetString("remindClientBeforeServing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed!.
        /// </summary>
        internal static string removeFailed {
            get {
                return ResourceManager.GetString("removeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove success!.
        /// </summary>
        internal static string removeSuccess {
            get {
                return ResourceManager.GetString("removeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-send.
        /// </summary>
        internal static string reSend {
            get {
                return ResourceManager.GetString("reSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Send code.
        /// </summary>
        internal static string reSendCode {
            get {
                return ResourceManager.GetString("reSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type.
        /// </summary>
        internal static string reType {
            get {
                return ResourceManager.GetString("reType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type password invalid!.
        /// </summary>
        internal static string reTypeInvalid {
            get {
                return ResourceManager.GetString("reTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retyping new password please!.
        /// </summary>
        internal static string retypeNewPasswordRequired {
            get {
                return ResourceManager.GetString("retypeNewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be less than {0} characters!.
        /// </summary>
        internal static string retypeNewPasswordTooLong {
            get {
                return ResourceManager.GetString("retypeNewPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type password is required!.
        /// </summary>
        internal static string reTypeRequired {
            get {
                return ResourceManager.GetString("reTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string roles {
            get {
                return ResourceManager.GetString("roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save location.
        /// </summary>
        internal static string saveLocation {
            get {
                return ResourceManager.GetString("saveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure code is required!.
        /// </summary>
        internal static string secureCodeRequired {
            get {
                return ResourceManager.GetString("secureCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure code must be less than {0} characters!.
        /// </summary>
        internal static string secureCodeTooLong {
            get {
                return ResourceManager.GetString("secureCodeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        internal static string securityCode {
            get {
                return ResourceManager.GetString("securityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more.
        /// </summary>
        internal static string seeMore {
            get {
                return ResourceManager.GetString("seeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a department.
        /// </summary>
        internal static string selectADepartment {
            get {
                return ResourceManager.GetString("selectADepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Doctor.
        /// </summary>
        internal static string selectDoctors {
            get {
                return ResourceManager.GetString("selectDoctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to.
        /// </summary>
        internal static string sendTo {
            get {
                return ResourceManager.GetString("sendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name.
        /// </summary>
        internal static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name is required!.
        /// </summary>
        internal static string serviceNameRequired {
            get {
                return ResourceManager.GetString("serviceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name must be less than {0} characters!.
        /// </summary>
        internal static string serviceNameTooLong {
            get {
                return ResourceManager.GetString("serviceNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string services {
            get {
                return ResourceManager.GetString("services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string shortFriday {
            get {
                return ResourceManager.GetString("shortFriday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string shortMonday {
            get {
                return ResourceManager.GetString("shortMonday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string shortSaturday {
            get {
                return ResourceManager.GetString("shortSaturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string shortSunday {
            get {
                return ResourceManager.GetString("shortSunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string shortThursday {
            get {
                return ResourceManager.GetString("shortThursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string shortTuesday {
            get {
                return ResourceManager.GetString("shortTuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string shortWednesday {
            get {
                return ResourceManager.GetString("shortWednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string signIn {
            get {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so we can let the customers know about them.
        /// </summary>
        internal static string soWeCanLetTheCustomersKnowAboutThem {
            get {
                return ResourceManager.GetString("soWeCanLetTheCustomersKnowAboutThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string statistics {
            get {
                return ResourceManager.GetString("statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subcriber SignUp.
        /// </summary>
        internal static string subcriberSignUp {
            get {
                return ResourceManager.GetString("subcriberSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your holidays.
        /// </summary>
        internal static string tellUsYourHolidays {
            get {
                return ResourceManager.GetString("tellUsYourHolidays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us your working hours (shifts) &amp; the maximum appointments you can handle per shift.
        /// </summary>
        internal static string tellUsYourWorkingHoursAndTheMaximumAppt {
            get {
                return ResourceManager.GetString("tellUsYourWorkingHoursAndTheMaximumAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string thankYou {
            get {
                return ResourceManager.GetString("thankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code had sent to.
        /// </summary>
        internal static string theCodeHadSentTo {
            get {
                return ResourceManager.GetString("theCodeHadSentTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        internal static string ticket {
            get {
                return ResourceManager.GetString("ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ticket was called !.
        /// </summary>
        internal static string ticketCalled {
            get {
                return ResourceManager.GetString("ticketCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ticket was cancelled.
        /// </summary>
        internal static string ticketCanceled {
            get {
                return ResourceManager.GetString("ticketCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Time was changed.
        /// </summary>
        internal static string ticketEstDateChanged {
            get {
                return ResourceManager.GetString("ticketEstDateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket list.
        /// </summary>
        internal static string ticketList {
            get {
                return ResourceManager.GetString("ticketList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ticket was re-scheduled.
        /// </summary>
        internal static string ticketPending {
            get {
                return ResourceManager.GetString("ticketPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ticket was pickuped to waiting list.
        /// </summary>
        internal static string ticketPickuped {
            get {
                return ResourceManager.GetString("ticketPickuped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} : Ticket sent to {1}.
        /// </summary>
        internal static string ticketSent {
            get {
                return ResourceManager.GetString("ticketSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} tickets found.
        /// </summary>
        internal static string ticketsFound {
            get {
                return ResourceManager.GetString("ticketsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string timeZone {
            get {
                return ResourceManager.GetString("timeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To date.
        /// </summary>
        internal static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed!.
        /// </summary>
        internal static string updateFailed {
            get {
                return ResourceManager.GetString("updateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success!.
        /// </summary>
        internal static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload photo.
        /// </summary>
        internal static string uploadPhoto {
            get {
                return ResourceManager.GetString("uploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is used in API to access our services from your web site or your app..
        /// </summary>
        internal static string usedApiToAccess {
            get {
                return ResourceManager.GetString("usedApiToAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details.
        /// </summary>
        internal static string userDetails {
            get {
                return ResourceManager.GetString("userDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string verify {
            get {
                return ResourceManager.GetString("verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify your account.
        /// </summary>
        internal static string verifyYourAccount {
            get {
                return ResourceManager.GetString("verifyYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View price list.
        /// </summary>
        internal static string viewPriceList {
            get {
                return ResourceManager.GetString("viewPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        internal static string waiting {
            get {
                return ResourceManager.GetString("waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting List.
        /// </summary>
        internal static string waitingList {
            get {
                return ResourceManager.GetString("waitingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website address must be less than {0} characters!.
        /// </summary>
        internal static string websiteTooLong {
            get {
                return ResourceManager.GetString("websiteTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When to restart ticket number.
        /// </summary>
        internal static string whenToRestartTicketNumber {
            get {
                return ResourceManager.GetString("whenToRestartTicketNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will take it.
        /// </summary>
        internal static string willTakeIt {
            get {
                return ResourceManager.GetString("willTakeIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to work days.
        /// </summary>
        internal static string workDays {
            get {
                return ResourceManager.GetString("workDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was created successfully!.
        /// </summary>
        internal static string yourAccountWasCreatedSuccessFully {
            get {
                return ResourceManager.GetString("yourAccountWasCreatedSuccessFully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API key.
        /// </summary>
        internal static string yourAPIKey {
            get {
                return ResourceManager.GetString("yourAPIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        internal static string yourPassword {
            get {
                return ResourceManager.GetString("yourPassword", resourceCulture);
            }
        }
    }
}
